DROP TABLE IF EXISTS User, Ticket ;

CREATE TABLE User(
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(20) NOT NULL,
password VARCHAR(200) NOT NULL,
email VARCHAR(150) NOT NULL,
role VARCHAR(1) NOT NULL
);

CREATE TABLE Ticket(
ID INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(100) NOT NULL,
language VARCHAR(100) NOT NULL,
description VARCHAR(300) NOT NULL,
creator VARCHAR(50) NOT NULL,
time_created TIMESTAMP NOT NULL,
time_updated TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
status VARCHAR(1) NOT NULL
);
